### ISSUE TITLE
文字错误

### ISSUE THREAD

**Issue by Lzzzzzq** [developerworks/learnnextjs-cn-docs#2]
第五章中，路由掩码部分最后

> 在 <Link> 元素中, 我们使用另外一个叫做 as 的熟悉. 这是我们需要显示在浏览器地址栏中的URL. 应用程序看到的实际URL是实际上是在 href 熟悉中

熟悉 应改为 属性。

**Comment by developerworks** [comment]
请PR, 谢谢.
